### ISSUE TITLE
Merge in Yoast SEO?

### ISSUE THREAD

**Issue by omarreiss** [ashhitch/wp-graphql-yoast-seo#1]
@ashhitch cool plugin! Would you consider creating a PR on https://github.com/Yoast/wordpress-seo to include this directly in the Yoast SEO plugin? We'd be happy to welcome you as a contributor!

**Comment by ashhitch** [comment]
@omarreiss thanks! Would love to see the plugin be part of the core 👍

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
