### ISSUE TITLE
Yoast Content Types - Enhancement

### ISSUE THREAD

**Issue by robmarshall** [ashhitch/wp-graphql-yoast-seo#10]
It would be great if this plugin could pull content from the "Content Types" tab under "Search Appearance".

This would mean Post and Custom Post Type archives could have titles/description meta handled from WordPress, rather than having to hard code this in Gatsby.

**Comment by ashhitch** [comment]
That's an interesting idea, wonder if it would be best to extend postTypeInfo to provide this, so you would end up with a query like this...
```
{
  posts {
    postTypeInfo {
      seo {
        title
        metaDesc
      }
    }
    nodes {
      title
 seo {
        title
        metaDesc
      }
    }
  }
}
```

**Comment by robmarshall** [comment]
Might be better creating a completely new typename. I say this due to all the smaller options within the section. Maybe more like this:

```
wpgraphql {
  seo {
    titleSeparator
    contentType {
      post {
        title
        metaDesc
      }
      page {
        title
        metaDesc
      }
    }
    taxonomies {
      categories {
        title
        metaDesc
      }
      tags {
        title
        metaDesc
      }
    }
  }
}
```

**Comment by ashhitch** [comment]
Finally got around to figuring this one out.
https://github.com/ashhitch/wp-graphql-yoast-seo/releases/tag/v4.8.0

**Comment by ravewebdev** [comment]
@ashhitch Could this be expanded to include CPT archive settings? E.g., `title-ptarchive-<cpt>` and `metadesc-ptarchive-<cpt>`

For instance, our project has the Team CPT and these settings are available in Yoast (but we cannot access them via GraphQL):
![Screen Shot 2021-01-28 at 12 58 22 PM](https://user-images.githubusercontent.com/36422618/106191765-858c7580-6168-11eb-9e95-1284d3b0888b.png)
`

**Comment by ashhitch** [comment]
Have you tried... 

```

wp {
  seo {
     contentTypes {
       YOURPOSTTYPE {
      title
       schemaType 
                           metaRobotsNoindex
       metaDesc
    }
}
}
}

```

**Comment by ravewebdev** [comment]
@ashhitch that query returns the single <post type> settings, not the settings for the <post type> _archive_.

e.g., the single Team CPT title and desc here are exposed via GraphQL:
![Screen Shot 2021-01-29 at 2 47 51 PM](https://user-images.githubusercontent.com/36422618/106330760-074fd200-6241-11eb-819c-919ee1a4674a.png)

but the Team CPT archive settings are not exposed:
![Screen Shot 2021-01-29 at 2 50 16 PM](https://user-images.githubusercontent.com/36422618/106330912-539b1200-6241-11eb-9844-557c02f570e7.png)
