### ISSUE TITLE
Recurring PHP notices about undefined indices (wpseo_metakeywords and canonical)

### ISSUE THREAD

**Issue by niklaslovgren** [ashhitch/wp-graphql-yoast-seo#101]
Since installing this plugin, these notices appear frequently in the logs. They appear in pair; one comes right after the other.

```log
PHP Notice:  Undefined index: wpseo_metakeywords in […]/wp-content/plugins/add-wpgraphql-seo/wp-graphql-yoast-seo.php on line 1113
PHP Notice:  Undefined index: canonical in […]/wp-content/plugins/add-wpgraphql-seo/wp-graphql-yoast-seo.php on line 1176
```

Is there something misconfigured on our side, or should this be handled by the plugin?

**Comment by ashhitch** [comment]
Hi thanks for reporting this I will take a look at this

**Comment by ashhitch** [comment]
I have added some guards around these properties in v4.14.2
Thanks for reporting the issue
