### ISSUE TITLE
Canonical link not appearing in post query

### ISSUE THREAD

**Issue by colbyfayock** [ashhitch/wp-graphql-yoast-seo#102]
I noticed that my canonical links are no longer showing up in my queries. I'm not really sure when this started happening, this is the first I noticed it.

I tested out on two separate wordpress instances and can't seem to get it working.

Query:
```
{
  posts {
    edges {
      node {
        title
        seo {
          canonical
        }
      }
    }
  }
}
```

![image](https://user-images.githubusercontent.com/1045274/120328905-4eb2a180-c2b9-11eb-90d4-81311f0aba78.png)

![image](https://user-images.githubusercontent.com/1045274/120328987-64c06200-c2b9-11eb-8bab-e9b4e68f0a4e.png)

**Comment by ashhitch** [comment]
@colbyfayock have you got the discourage search engines option ticked?
Yoast will not return a canonical if this option is ticked.

**Comment by colbyfayock** [comment]
yup that did it 🤦 thanks
