### ISSUE TITLE
GraphQL queries getting logged in Index Database

### ISSUE THREAD

**Issue by nhankla-kl** [ashhitch/wp-graphql-yoast-seo#103]
Hi,
We are running a site that failed the other day due to Yoast SEO logging every GraphQL query and filling up the index table with 20million records.

Not sure how we can disable that or remove the indexing as it is not needed. 

Odd issue for sure.

**Comment by ashhitch** [comment]
I will take a look at this, but my plugin does not do any logging… and my understanding is that the table stores a single record for every post, page, term. image etc on your site. What versions of Yoast, WpGraphQL, and Yoast WPGraphQL are you running?

**Comment by ashhitch** [comment]
@nhankla-kl  did you get to the bottom of this your end?
