### ISSUE TITLE
Seo for site?

### ISSUE THREAD

**Issue by fatlinesofcode** [ashhitch/wp-graphql-yoast-seo#11]
Hi,
I've installed the plugin. Works great for getting a page's Seo, but it possible to get the global site seo via graphql?

**Comment by ashhitch** [comment]
@fatlinesofcode Currently we only have SEO data for pages/posts/ custom post types and taxonomies.
However, I would like to expand this further, we have been talking about something simular in this issue: #10

**Comment by nathobson** [comment]
Also would be great if we could get access to the default social media images. These are really handy to have access too, especially on site with a high volume of pages where it's not practical for a page/post to always have a unique Open Graph/Twitter image set. 

I'll have a dig around `gatsby-source-wordpress` and see how they handled. that

**Comment by ashhitch** [comment]
Hi @fatlinesofcode and @nathobson 
I have just merged in #25 which provides site-level Yoast data including:

-  Webmaster verification
-  Social profiles
-  Schemas
-  Breadcrumbs

you can query the data from the root:
```
 seo {
    webmaster {
      googleVerify
      yandexVerify
      msVerify
      baiduVerify
    }
    schema {
      companyLogo {
        mediaItemUrl
...other media fields
      }
      logo {
        mediaItemUrl
      }
      personLogo {
        mediaItemUrl
      }
    }
    breadcrumbs {
      showBlogPage
      separator
      searchPrefix
      prefix
      homeText
      enabled
      boldLast
      archivePrefix
      notFoundText
    }
    social {
      facebook {
        url
        defaultImage {
          mediaItemUrl
        }
      }
      instagram {
        url
      }
      linkedIn {
        url
      }
      mySpace {
        url
      }
      pinterest {
        url
        metaTag
      }
      twitter {
        cardType
        username
      }
      wikipedia {
        url
      }
      youTube {
        url
      }
    }
  }

```

**Comment by ashhitch** [comment]
If there is anything I missed that you think should be added feel free to open another issue.

**Comment by ashhitch** [comment]
If there is anything I missed that you think should be added feel free to open another issue.
