### ISSUE TITLE
Yoast Premium - The WPGraphQL Yoast SEO plugin can't be loaded because these dependencies are missing:

### ISSUE THREAD

**Issue by unmaskz** [ashhitch/wp-graphql-yoast-seo#113]
Issue with plugin when using Yoast Premium:

> The WPGraphQL Yoast SEO plugin can't be loaded because these dependencies are missing:
> 
> Yoast SEO

**Comment by bjornlarus** [comment]
I am having the same issue @ashhitch , Yoast SEO Premium version 9.5 and WPGraphQL SEO version Version 4.16.0

**Comment by ashhitch** [comment]
@bjornlarus Yoast premium is currently on 17.7

Is there a reason your on v9?

I don't think my plugin will support a version that old I'm afraid.

**Comment by ashhitch** [comment]
Closing this as i believe it only relates to old incompatible yoast versions
