### ISSUE TITLE
Bump Composer Requirements

### ISSUE THREAD

**Issue by bringmethedeathstar** [ashhitch/wp-graphql-yoast-seo#12]
I'm getting the following when trying to `composer require ashhitch/wp-graphql-yoast-seo`:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for ashhitch/wp-graphql-yoast-seo ^2.1 -> satisfiable by ashhitch/wp-graphql-yoast-seo[v2.1.0].
    - ashhitch/wp-graphql-yoast-seo v2.1.0 requires wp-graphql/wp-graphql ^0.3.8 -> satisfiable by wp-graphql/wp-graphql[v0.3.8] but these conflict with your requirements or minimum-stability.

Installation failed, reverting ./composer.json to its original content.
```

My project requires `"wp-graphql/wp-graphql": "^0.4.2"` in order to use `wp-graphql/wp-graphql-acf`, which has a minimum requirement of `"wp-graphql/wp-graphql": "^0.4.0"`.

Is it possible to bump the required version of `wp-graphql/wp-graphql` within your `composer.json`?

**Comment by ashhitch** [comment]
Hey, I have just changed the composer file to use >= I think this will solve your issue.

**Comment by bringmethedeathstar** [comment]
Perfect - cheers 🎉
