### ISSUE TITLE
Cannot return null for non-nullable field "MediaItem.id"

### ISSUE THREAD

**Issue by ttstauss** [ashhitch/wp-graphql-yoast-seo#132]
When running a query for `twitterImage?.sourceUrl()` I get the following error (when no image has been added to the Twitter preview/Twitter Image section in WordPress):
```
[GQtyError: Internal server error] {
  graphQLErrors: [
    {
      debugMessage: 'Cannot return null for non-nullable field "MediaItem.id".',
      message: 'Internal server error',
      extensions: [Object],
      locations: [Array],
      path: [Array]
    }
  ]
}
```
Doesn't seem to be an issue with `opengraphImage?.sourceUrl()`

**Comment by justlevine** [comment]
Betting it has to do with [this](https://github.com/ashhitch/wp-graphql-yoast-seo/blob/c0ceb835276b6309ea9a8d1271802e6604b603e0/wp-graphql-yoast-seo.php#L754), where `wpcom_vip_attachment_url_to_postid` is returning false causing a `0` to be passed to the loader instead of bailing with null.

**Comment by robmarshall** [comment]
I am also running into this issue.

**Comment by macojaune** [comment]
Hi, are there any news on this issue ?

**Comment by ashhitch** [comment]
Thanks @izzygld for taking a look this one
