### ISSUE TITLE
Missing isPrimary field on taxonomy edges in latest update

### ISSUE THREAD

**Issue by mikenolan** [ashhitch/wp-graphql-yoast-seo#137]
The latest update appears to drop the isPrimary field from taxonomy edges but the changelog doesn't make any reference to this breaking (for us) change.

**Comment by ashhitch** [comment]
Sorry about they issues the latest release has caused will try to get the resolved as soon as possible as it should still be there

**Comment by ashhitch** [comment]
@mikenolan @evangelinepapanicola just to let you know the data is back in the latest release v4.18.1.
Sorry for the trouble it caused over the weekend.

**Comment by evangelinepapanicola** [comment]
No worries - thanks for the quick fix!
