### ISSUE TITLE
Yoast Config Data (socials) - plugin is not updated to the newest Yoast data structure

### ISSUE THREAD

**Issue by code-runner92** [ashhitch/wp-graphql-yoast-seo#138]
### Yoast Version 17.7.1

Yoast provided individual inputs for specific social platforms:

![Screenshot 2022-06-27 at 22 23 04](https://user-images.githubusercontent.com/17150224/176030017-5f384e4a-ad18-44e1-9e4a-a1d0588c3c74.png)

and it was reflected in this graphQL plugin:
```
social {
    facebook {
        url
        defaultImage {
            mediaItemUrl
        }
    }
    instagram {
        url
    }
    linkedIn {
        url
    }
    mySpace {
        url
    }
    pinterest {
        url
        metaTag
    }
    twitter {
        cardType
        username
    }
    wikipedia {
        url
    }
    youTube {
        url
    }
}
```

### Yoast Version 19.1

Yoast provides _named_ inputs only for Facebook and Twitter. All the rest are _platform-agnostic_.

![Screenshot 2022-06-27 at 22 24 24](https://user-images.githubusercontent.com/17150224/176030395-5a225192-8ee7-4e4c-a3f0-bc7fa993b64b.png)

⚠️ You can fetch Facebook and Twitter data with following query but it's not possible to get the rest of fields. ⚠️

```
social {
    facebook {
        url
        defaultImage {
            mediaItemUrl
        }
    }
    twitter {
        cardType
        username
    }
}
```

**Comment by ashhitch** [comment]
Sorry about the delay in getting this done. 
v4.19.0 contains these profiles
