### ISSUE TITLE
Can't see yoast "isPrimary" edge for post categories.

### ISSUE THREAD

**Issue by AndrzejBaran** [ashhitch/wp-graphql-yoast-seo#140]
Using Gatsby.JS with GraphQL. I can see all nodes for seo, but edges are not showing, so I can't grab isPrimary. 
My query looks like this:
```
query getPost {
  wpPost(databaseId: {eq: 12}) {
    categories {
      edges {
        isPrimary
      }
      nodes {
        link
        name
      }
    }
    content
    author {
      node {
        email
        name
        uri
      }
    }
    seo {
      title
    }
  }
}
```

This gives me an error "Cannot query field \"edges\" on type \"WpPostToCategoryConnection\". Did you mean \"nodes\"?". If I remove edges it works. Seo also gives corrrect values, but not edges.

**Comment by ashhitch** [comment]
@AndrzejBaran  unfortunately Gatsby does not support edge fields
