### ISSUE TITLE
No query avaiable to get homepage seo data

### ISSUE THREAD

**Issue by H-Nguyenx** [ashhitch/wp-graphql-yoast-seo#142]
Hi, I can not find graphql query to retrieve homepage seo information in the image below through wp-graphql-yoast-seo plugin.
There is only social information of homepage query avaiable.
![Screenshot_20221111_034517](https://user-images.githubusercontent.com/33373945/201301905-64f0d4d0-ffc6-412a-862a-686d53fc7ef1.png)

**Comment by ashhitch** [comment]
Hey, i should be able to get this added in for you

**Comment by ashhitch** [comment]
@cantoute this is in [v4.20.0](https://github.com/ashhitch/wp-graphql-yoast-seo/tree/v4.20.0)

```graphql
query GetSeoConfig {
    seo {
        meta {
            author {
                description
                title
            }
            config {
                separator
            }
            homepage {
                description
                title
            }
            notFound {
                breadcrumb
                title
            }
        }
}
```
