### ISSUE TITLE
No way to query date archive SEO settings

### ISSUE THREAD

**Issue by marcusforsberg** [ashhitch/wp-graphql-yoast-seo#148]
As far as I can tell, there currently is no way to query the SEO settings for date archives, as set in Search Appearence in Yoast:

<img width="675" alt="Screen Shot 2023-01-19 at 4 44 39 PM" src="https://user-images.githubusercontent.com/1009069/213488018-9bc56efa-7d49-4046-ba48-cf6321c7395e.png">

Are there any plans to implement something like this or any pointers on how it could be done so I can get started on a PR? :)

**Comment by ashhitch** [comment]
@marcusforsberg 
v4.22.0   has just been published with Date archive title and description

```graphql
query GetSeoConfig {
    seo {
        meta {
            date {
                description
                title
            }
        }
    }
}
```

**Comment by marcusforsberg** [comment]
Thanks, this works. 

However, is there any way to add a dynamic query for this where you can specify a specific date? In the Yoast Settings, you can add a "Date" variable which is normally replaced with the actual date. Being able to utilize that variable in GraphQL would be quite powerful.

Consider a date archive setup such as this:

![Screen Shot 2023-02-16 at 4 43 56 PM](https://user-images.githubusercontent.com/1009069/219415644-b0b3f612-9cb3-41c7-b5d6-d465c866fe1c.png)

The query would return:

```json
"seo": {
  "meta": {
    "date": {
      "description": "",
      "title": "Posts from: - my-site"
    }
  }
}
```

There's no way for the client to know where to inject the date since the "date" variable has been stripped away.

Would it be possible to implement a custom query type such as this (with month and day being optional)?

```gql
query GET_DATE_ARCHIVE_SEO {
  dateSeo(year: 2023, month: 2, day: 16) {
    description
        title
  }
}

**Comment by marcusforsberg** [comment]
Thanks, that works. I have a suggestion for a potential improvement which I've added a new issue for: #151
