### ISSUE TITLE
SEO - Canonical Support

### ISSUE THREAD

**Issue by kvindasAB** [ashhitch/wp-graphql-yoast-seo#16]
Hello Guys,

Thanks a lot for this plugin.

I'm currently building an eCom Site and I'm using this plugin to grab Yoast SEO.

Although I have noticed that the `canonical` configured in Yoast for pages or Posts is not being retrieved.

The `canonical` can be found in the advanced tab of the Yoast section for the page and post.

**Comment by ashhitch** [comment]
@kvindasAB thanks for reporting this I will take a look.
