### ISSUE TITLE
WooCommerce - Product Pages Support

### ISSUE THREAD

**Issue by kvindasAB** [ashhitch/wp-graphql-yoast-seo#17]
Hello Guys,

I'm building an ecom site and using this plugin to retrieve Yoast SEO configuration.

Although I get all the SEO information for  Pages/Posts and even ProductCategories, Products in specific retrieve no information at all.

**Comment by ashhitch** [comment]
@kvindasAB  I have yet to do any testing with WooCommerce I will setup and instance and see what I can do

**Comment by ashhitch** [comment]
@kvindasAB i now have a branch where I am working Woocomerce support:
https://github.com/ashhitch/wp-graphql-yoast-seo/tree/feature/woocommerce

Currently have support for products

**Comment by kvindasAB** [comment]
@ashhitch Will test it.

Thanks a lot

**Comment by kvindasAB** [comment]
Hello @ashhitch , I have been testing the branch and seems to be working right.
