### ISSUE TITLE
metaRobotsNofollow and metaRobotsNoindex not working

### ISSUE THREAD

**Issue by wbertolo** [ashhitch/wp-graphql-yoast-seo#175]
Hi Ash,

Congrats on the plugin development. It is a helpful tool. Overall, works great.

I am having one issue though. While fields like Title and Meta Description are being returned with correct content, `metaRobotsNofollow` and `metaRobotsNoindex` are always returning `nofollow` and `noindex` even though both the general settings and the page settings are set to `Yes` (to index).

Would that be a known issue?

Thanks in advance,

**Comment by ashhitch** [comment]
@wbertolo only if you have Discourage search engines from indexing this site option ticked. This comes from Yoast

**Comment by wbertolo** [comment]
@ashhitch , hi, sorry for the bug. It was due to an internal feature. I will close this.
