### ISSUE TITLE
Multiple CPT's all share the same SEO metadata

### ISSUE THREAD

**Issue by haxmart** [ashhitch/wp-graphql-yoast-seo#176]
When registering multiple CPT's using ACF, the query for the SEO data for the CPT archives share the same metadata, despite this being manually set to something different in the YOAST settings.

Removing multiple CPT's and just having one is the only way i'm currently able to get the right metadata to be returned.

<img width="936" alt="Screenshot 2024-08-01 at 14 13 17" src="https://github.com/user-attachments/assets/2f4d4584-faa2-495e-a1b4-8e6ad9b6902b">

**Comment by ashhitch** [comment]
@haxmart i know this is really late.
I have tested this and can replicate the issue.

I tries CPT UI and then switched to the ACF version and both worked as expected

<img width="1255" alt="Screenshot 2024-12-16 at 21 57 22" src="https://github.com/user-attachments/assets/e87d66b3-88ab-40fd-bce7-9869cb0dcb4b" />
