### ISSUE TITLE
ProductCategory SEO title not generated correctly.

### ISSUE THREAD

**Issue by kvindasAB** [ashhitch/wp-graphql-yoast-seo#19]
Hello Guys,

I have been using this plugin and I have noticed the following.

For productCategories in specific I'm currently getting the title in the following format:

```
48 - product_cat -MySEOTitleOverHere...
```

So basically every category have this prefix `48 - product_cat -` with the database and the word `product_cat`.

At the moment I'm patching the result on client side to correct this, but seems to be an error.

**Comment by ashhitch** [comment]
Thank for spotting this, just removed the debug info thay made it into master
