### ISSUE TITLE
Add dynamic meta data

### ISSUE THREAD

**Issue by shendriksza** [ashhitch/wp-graphql-yoast-seo#2]
Does this plugin still work with wp-graphql 0.3.2 (after the major 0.3.0 overhaul)? I did a quick test and it seems the graphql queries only return data when you manually edited the meta tags with the plugin. All autogenerated Yoast entries are empty strings

**Comment by jchrislemmer** [comment]
The plugin works, however, the issue we're seeing is that the dynamically generated content isn't being fetched.

I other-words, if you configure Yoast with a global meta description, it doesn't work. You have to specifically set one on that page in order to get it.

Thanks
Chris

**Comment by ashhitch** [comment]
This is correct, currently, it does just pull the data from the meta fields. Which is only populated if you manually change the fields...
I do plan to try to add this soon

**Comment by jchrislemmer** [comment]
Okay, cool, thank you!

**Comment by jchrislemmer** [comment]
Btw, is it also possible to add the meta-data for WordPress blog categories?

Thanks
Chris

**Comment by ashhitch** [comment]
@jchrislemmer great suggestion will add this to the roadmap

**Comment by jchrislemmer** [comment]
Hey there,

Any idea when this will work?

Kind regards
Chris

**Comment by ashhitch** [comment]
@jchrislemmer sorry been a bit snowed under with work lately, however, I have made some progress with this... if you use this branch: https://github.com/ashhitch/wp-graphql-yoast-seo/tree/feature/dynamic-data
You will get dynamic title and descriptions (if you have set up the dynamic descriptions in the Yoast plug) 
Would be great to get any feedback you have before I merge this into master

**Comment by jchrislemmer** [comment]
Hey @ashhitch thanks for this! I'll definitely give it a go and send you feedback.

**Comment by shendriksza** [comment]
Thanks @ashhitch the plugin is looking really good so far! The dynamic data is almost perfect now, but we are seeing a problem with the title response:

`"title": "Terms and Conditions",`
`"seo": {`
`"title": "| Site Title",`
`}`

This is with a title using the following snippets: `title page sep sitename `
For some reason, all snippets except the title were populated in the SEO title. The title and other snippets work fine when used in another field such as description, only the title did not populate correctly

**Comment by ashhitch** [comment]
@shendriksza thank for the feedback will take a look into this.
