### ISSUE TITLE
Wordpress error when running gatsby develop

### ISSUE THREAD

**Issue by pmkemper** [ashhitch/wp-graphql-yoast-seo#22]
Hey,

I got the following error in Wordpress when I ran `gatsby develop` locally, with wp-graphql-yoast-seo, WP GraphQL, and WP Gatsby installed, as well as WPML (posts in various languages):

> PHP Recoverable fatal error: Object of class WPGraphQL\\Model\\Post could not be converted to string in /.../wp-content/plugins/wordpress-seo/frontend/class-frontend.php on line 563

I could fix this error by editing line 75 of your plugin (adding "->post_title"):
`              'title' => trim($wpseo_frontend->title($post->post_title)),
`

**Comment by ashhitch** [comment]
@pmkemper thanks for raising the bug, do you know if the issue only happens when WPML is enabled?

**Comment by pmkemper** [comment]
I haven't tried with WPML disabled. However, if you check here: https://github.com/Yoast/wordpress-seo/blob/trunk/frontend/class-frontend.php you see that the the title method accepts a string as an argument, while this plugin passes it a post object. Hence why I think passing it $post->post_title works and passing it just $post does not.

**Comment by ashhitch** [comment]
Fixed by #23
