### ISSUE TITLE
Expose googlebot default value

### ISSUE THREAD

**Issue by thmsnhl** [ashhitch/wp-graphql-yoast-seo#26]
Would it be possible to expose the content of the googlebot field to graphql? 

Currently I don't see a way to utilize the data provided to build consistent meta tags across the rendered frontend and an application that consumes the graphql endpoint.

**Comment by ashhitch** [comment]
Hey, @thmsnhl could you provide a little more info on what you are after?

For the post types we already expose:

- metaRobotsNoindex
- metaRobotsNofollow

**Comment by thmsnhl** [comment]
Hey @ashhitch thanks for reaching out and sorry, that my request was not clear enough.
metaRobotsNoindex and metaRobotsNofollow return values of `0` an `1` but if you take a look into pages that have been rendered by wordpress, you see that the meta robots-tag contains `max-snippet:-1, max-image-preview:large, max-video-preview:-1`.

I would like to get this value out of the graphql endpoint, so that I can use it in a vue.js application, that is linked to the wordpress site. 

For reference: the value is set in yoast-seo `Line 235 of src/presentations/indexable-presentation.php` 

I hope this is clear enough and you can help me with this :)

**Comment by ashhitch** [comment]
Hi 
I have just been looking into this and `max-snippet:-1, max-image-preview:large, max-video-preview:-1` seems to be a fixed value? 

What advantage would you get by putting this into the GraphQl response?
Could you not just add `<meta name="robots" content="max-snippet:-1, max-image-preview:large, max-video-preview:-1"/>` into the layout as it does not change?  

Or am I missing something?

**Comment by thmsnhl** [comment]
When I opened up the issue I had no access to the yoast advanced settings, I thought it is possible to set this value via yoast but apparently it is not. 

With this in mind the only benefit of providing this in the response would be to keep it up-to-date when yoast decides to change it in a future version. 

So feel free to close the issue, if this does not seem to be relevant enough for you.

**Comment by ashhitch** [comment]
Will keep an eye on this and add it if it becomes dynamic
