### ISSUE TITLE
Extract Homepage title and description

### ISSUE THREAD

**Issue by rohitb4** [ashhitch/wp-graphql-yoast-seo#27]
Is there any way to extract Homepage title and description?  Please refer to the screenshot below.
<img width="948" alt="Screenshot 2020-04-12 at 6 15 22 PM" src="https://user-images.githubusercontent.com/6358889/79069160-aa068680-7ce9-11ea-88f2-d95a54675555.png">

**Comment by ashhitch** [comment]
Hey, currently this is not available in the plugin, but I will add this to the roadmap

**Comment by dulx96** [comment]
Waiting for new update

**Comment by ashhitch** [comment]
Sorry about the delay but this is in the latest release https://github.com/ashhitch/wp-graphql-yoast-seo/releases/tag/v4.5.0
