### ISSUE TITLE
Update plugin to work with Yoast 14

### ISSUE THREAD

**Issue by ashhitch** [ashhitch/wp-graphql-yoast-seo#30]
#29 #28

**Comment by ashhitch** [comment]
Progress can be followed here:
https://github.com/ashhitch/wp-graphql-yoast-seo/tree/feature/yoast-14

**Comment by izzygld** [comment]
@ashhitch thanks for the quick fixes to yoast v14 helped us alot. :thumbsup:

Any particular reason you didn't add the "canonical" field to the example in ReadMe?

**Comment by ashhitch** [comment]
@izzygld its not in the readme on because I have not got around to updating it yet. 🙈

Any PRs are always welcome! Will try get the lasted work into master later, which might make it easier.

**Comment by izzygld** [comment]
ok. thanks.

Let me know when you've merged v14 into master.

**Comment by ashhitch** [comment]
@izzygld  V4 of the plugin is now in master.
