### ISSUE TITLE
metaDesc returning same content for all posts

### ISSUE THREAD

**Issue by robmarshall** [ashhitch/wp-graphql-yoast-seo#39]
When a number of posts is queried, the metaDesc content is taken from the first post and applied to all in that list.

This can be replicated in the GraphiQL editor - no changes made to theme.

**Comment by ashhitch** [comment]
Hi @robmarshall 
Can I ask what version of the plugin you are using and which version of Yoast you are using?

**Comment by robmarshall** [comment]
ah, Ill upgrade and check that out!
