### ISSUE TITLE
Add authors to schema

### ISSUE THREAD

**Issue by saleebm** [ashhitch/wp-graphql-yoast-seo#42]
Hey,
I see the branch feature/authors available, but is there any reason why the authors are not included with the user object that I am missing? I was hoping to add social links, but not if there is an issue I'm missing. I saw #18 (closed) but there was no info there.

Thank you.

**Comment by ashhitch** [comment]
Hey, yeah I put this one on the back burner while I worked on some other features and support for the newer version of Yoast, will try to get back to it soon.

**Comment by ashhitch** [comment]
v4.4.0 Includes support for Author data.
