### ISSUE TITLE
Doesn't work when Yoast SEO was activated as MU-plugin

### ISSUE THREAD

**Issue by kovordaniy** [ashhitch/wp-graphql-yoast-seo#47]
`'Yoast SEO'        => is_plugin_active( 'wordpress-seo/wp-seo.php' ) || is_plugin_active( 'wordpress-seo-premium/wp-seo-premium.php' );`

Because of

`function is_plugin_active( $plugin ) {
	return in_array( $plugin, (array) get_option( 'active_plugins', array() ) ) || is_plugin_active_for_network( $plugin );
}`

If Yoast SEO was activated as mu-plugin it doesn't appear in **active_plugins** option.

Please add a safer check condition

**Comment by ashhitch** [comment]
Thanks for highlighting this I will look into a better way of checking

**Comment by ashhitch** [comment]
FIxed by #48 in v4.4.1
