### ISSUE TITLE
Breadcrumb shows Tags instead of Categories (sometimes)

### ISSUE THREAD

**Issue by JimCaignard** [ashhitch/wp-graphql-yoast-seo#49]
The plugin is well set but on some posts in a random way, the breadcrumb shows a Tag and not a Category as asked ! 

<img width="785" alt="Capture d’écran 2020-07-06 à 19 55 38" src="https://user-images.githubusercontent.com/5680997/86623924-b46fae00-bfc2-11ea-8637-a2d3d5d7c820.png">

**Comment by ashhitch** [comment]
Have you got an example of the query you are running? 
I wonder if it’s some fallback value? As I just pass through the result from Yoast.
