### ISSUE TITLE
Request: JSON+LD for individual posts.

### ISSUE THREAD

**Issue by rauschmerscen** [ashhitch/wp-graphql-yoast-seo#53]
Yoast puts Json+ld automatically in the article generated by wordpress itself. 
It would be awesome if the same Json+ld object is automatically available in the post's seo.

**Comment by ashhitch** [comment]
I have started to look at this, mainly around creating an example using React Helmet as the plugin provides all the data to compose it yourself.

I don't think we would want to take the full data wholesale directly from Yoast as they present information like the default WordPress search information.

Maybe it needs to be the post specific parts returned🤔.

**Comment by rauschmerscen** [comment]
> Maybe it needs to be the post specific parts returned

Yes

**Comment by izzygld** [comment]
i created awhile back [https://github.com/izzygld/wp-graphql-google-schema](https://github.com/izzygld/wp-graphql-google-schema) a google schema.

@ashhitch would be amazing to create a "Add-On" to this already wonderful wp-graphql-yoast-seo plugin.

**Comment by garusky** [comment]
Hi @ashhitch is this functionality taken into account? 
It would be really useful to have it 🙂

**Comment by izzygld** [comment]
The question is how far do we want to take it?

i see Yoast v14.8 Adds a Schema section to the metabox and sidebar. This section allows the user to change their Schema settings on posts, pages and custom post types
.
 https://yoast.com/structured-data-schema-ultimate-guide/ 

any thoughts here?

**Comment by ashhitch** [comment]
I was going to return the whole schema trouble is it returns stuff like the wordPress search. 
I think it's best to return the required data to build up a schema to your own needs.

But happy to get some further input.

I'm currently working on a demo of this with Gatsby.

@izzygld will take a look at the new schema features and see what we can use.

**Comment by pierreavizou** [comment]
Would work great for my use case to get the same schema as currently returned by Yoast on the Rest API (including WP search etc). 

Having the same data returned from GraphQL would probably allow for an easier, smoother transition. 

Currently the data returned by wp-graphql-yoast-seo does not allow to manually build a schema equivalent to what Yoast builds internally / returns on REST API, i.e schema.org author/person '@id. 

So my input on this would be let the plugin return the whole Yoast schema, and since this is just JSON, the user can easily apply treatment on it should it be needed.

**Comment by ashhitch** [comment]
v4.10.0 includes the raw Schema data. 
Sorry, it's taken a while to get to this feature.
Its returned as an encoded string ... I do plan to add a more structured version in the future to complement this.

example query:

```
{
  pages {
    nodes {
      title
      seo {
        title
        metaDesc
        schema {
          pageType
          articleType
          raw
        }
      }
    }
  }
}

```
