### ISSUE TITLE
Get Yoast Primary Category in Post

### ISSUE THREAD

**Issue by shabith** [ashhitch/wp-graphql-yoast-seo#57]
Hi there, 

Thanks for this great plugin 👍 

Is it possible to get **_Yoast_** Primary Category in graphql?

**Comment by ashhitch** [comment]
That's a great suggestion will just need a little planning for the best approach, as we would need to do it for custom taxonomies too, a couple of idea of how we could build this in...

Something like this:
```
query MyQuery {
  posts {
    nodes {
      title
      categories {
        nodes {
          name
          seo {
            isPrimary # true / false
          }
        }
      }
    }
  }
}
```

Or this:
```
query MyQuery {
  posts {
    nodes {
      title
      seo {
        primaryCategory {
          name
        }
      }
      categories {
        nodes {
          name
        }
      }
    }
  }
}
```

**Comment by shabith** [comment]
hmm, for me first approach looks good.

**Comment by ashhitch** [comment]
@shabith its been a while but finally got around to adding this feature... 
Primary Term for posts (and other post types) has been added to edge with isPrimary boolean field
Its had to be added to the edge to gather the data required.
```
query GetPostsPrimary {
  posts {
    nodes {
      title
      slug
      categories {
        edges {
          isPrimary
          node {
            name
            count
          }
        }
      }
    }
  }
}
```

**Comment by shabith** [comment]
Great news! Thanks a lot @ashhitch

**Comment by AndrzejBaran** [comment]
Hi! Can you add same option for wpPost query? It's available only in post collection query and I need to get primary category in single post query. Much appreciated!
