### ISSUE TITLE
cardType appears in WP GraphiQL but not in Gatsby GraphiQL

### ISSUE THREAD

**Issue by nunof07** [ashhitch/wp-graphql-yoast-seo#58]
Hi,

I'm trying to get this:

```graphql
{
  seo {
    social {
      twitter {
        cardType
      }
    }
  }
}
```

To appear in a Gatsby site running `gatsby-source-wordpress-experimental`. However, the `cardType` field is always missing on the Gatsby side.

I can confirm the value appears correctly in WP GraphiQL.
I can also confirm the value appears correctly using GraphQL Playground connected to the WP site.

But in Gatsby, the `cardType` field is never recognized.

As a side note, I can confirm other general settings can be queried successfully, such as the `username` field that exists under the same `twitter` object.

I also mentioned this issue in the `gatsby-source-wordpress-experimental` repository: https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/issues/111#issuecomment-671382946 (second part of the comment).

Any idea if the issue might be in this WP plugin?

Thanks.

**Comment by ashhitch** [comment]
@nunof07 Thanks for raising this. I think it could related to the field being an enum. 
I have commented on you issue here:
https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/issues/111#issuecomment-672687447

**Comment by nunof07** [comment]
Thank you for the follow up, @ashhitch . I think we'll continue the discussion on the other issue.

**Comment by ashhitch** [comment]
Closing as but on Gatsby plugin... if enum's become a problem we could look at changing this in the future
