### ISSUE TITLE
opengraphImage and twitterImage not showing in API

### ISSUE THREAD

**Issue by Mactory** [ashhitch/wp-graphql-yoast-seo#60]
Hi,

I have a page with both, the opengraph image and twitter image set, but both fields, `opengraphImage` and `twitterImage` show up as `null` in the API.

I have looked at the code and found the following problems: The value for `YoastSEO()->meta->for_post($post->ID)->open_graph_images`, which is used to retrieve the value for the open graph image, returns the images as an array or arrays. From the first image in the array, the `url` is taken and then put through wp's `attachment_url_to_postid` function to retrieve the `id`. Unfortunately, the URL in the array is a scaled Version of the original image, meaning that it has the dimensions of the thumbnail attached to the original filename (eg. `my-image-1640x680.jpg`). The `attachment_url_to_postid` function can't find the media attachment with this URL and returns 0, resulting in a null value for the API.

A similar problem exists for the twitter image, where the `YoastSEO()->meta->for_post($post->ID)->twitter_image` call returns a scaled version of the image, resulting in a return value of 0 from the `attachment_url_to_postid` function.

The problem with `opengraphImage` could possibly be overcome by using one of the other values in the image array. In my example, the array contains an `id` field, which could be used directly. However, I'm unsure if this value is always available.

I would also like to ask, wether it is necessary to return the images as `MediaItems` instead of as simple URLs. Yoast returns the scaled versions of the images, since they are optimized for the specific use-case. By expanding them back to MediaItems, the implementation that uses the information needs to re-decide which size to use.

I can offer to implement the changes if you like, but wanted to discuss the topic before creating a pull request.

Thank you for a great plugin!

**Comment by ashhitch** [comment]
Hi,
Thanks for reporting this. 
We need to return the images as `MediaItems` as this how images work with the main WpGraphQL plugin and then plays nicely with frameworks like Gatsby.

I have not seen this happen myself so will take a look, have you got any live examples? 

I do very much welcome any PRs if you have any ideas on how to resolve this without any breaking changes to the API.

**Comment by rodrigo-arias** [comment]
I found the same problem and came to the same conclusion of @Mactory. Just one detail, if I use the default image from _SEO Social > Facebook > Default settings_, the `opengraphUrl` node works, although of course, it is the fallback image and not that of each post.

**Comment by ashhitch** [comment]
Hi
I am going to take another look at this one as my next task

**Comment by nparsons08** [comment]
Hi there, just wanted to see if there has been any progress on this. Looks like it's been 17 days. We are also seeing an issue on our end with OG images as described above.

**Comment by Mactory** [comment]
Hi, sorry for not getting back on this since reporting it. 

I have implemented a workaround for my use-case that does not comply with the `MediaItem` structure and instead returns the URLs of the correctly scaled images from Yoast SEO directly. 
In my tests, `YoastSEO()->meta->for_post($post->ID)->open_graph_images`  returns an `id` that can be used to generate the `MediaItem` but I did not find a solution to do the same for the `twitter_image` as Yoast SEO only returns the URL of the scaled image in my tests. I could not find a way to get the original image id from that.

I then decided to use the URLs directly, as it works perfectly fine for my use-case.

If you like, I can offer to add these URLs as graphql fields that could be named something like `scaledOpengraphImageURL` and `scaledTwitterImageURL` in a PR.

**Comment by ashhitch** [comment]
Sorry I have not got to this yet but 
I would be happy to accept a PR with a separate field.

**Comment by Mactory** [comment]
I was just working on the PR, when I stumbled upon the function `get_attachment_by_url` [here](https://github.com/Yoast/wordpress-seo/blob/trunk/inc/class-wpseo-image-utils.php) which  seems to do exactly what we need to retrieve the image id from scaled images, solving the original problem. I will give this a try.

**Comment by ashhitch** [comment]
@Mactory yes good spot, just been looking through this and it could be as simple as adding 
```
$url = preg_replace( '/(.*)-\d+x\d+\.(jpg|png|gif)$/', '$1.$2', $url );

		static $uploads;

		if ( $uploads === null ) {
			$uploads = wp_get_upload_dir();
		}

		// Don't try to do this for external URLs.
		if ( strpos( $url, $uploads['baseurl'] ) !== 0 ) {
			return 0;
		}
```
to the `wp_gql_seo_format_string` function

**Comment by ashhitch** [comment]
I have now published the code that should filter out the sizing for the ID lookup.
Still, feel free to PR a change to add the raw URL if you think this will be helpful too.
