### ISSUE TITLE
"seo" disappeared from category

### ISSUE THREAD

**Issue by erick-go** [ashhitch/wp-graphql-yoast-seo#65]
Hi!

I no longer see the seo object in the category object. I'm using gatsby-source-wordpress-experimental, but I've checked, and it also doesn't appear in WpGraphiql Wordpress plugin.

Downgrading to https://github.com/ashhitch/wp-graphql-yoast-seo/archive/v4.6.0.zip fixed it for now.
WpGraphQL 0.13.2
gatsby-source-wordpress experimental 1.5.3

**Comment by ashhitch** [comment]
Thanks for the heads up will take a look at this.

**Comment by ashhitch** [comment]
Fixed by v4.7.1
