### ISSUE TITLE
Special characters printing out like &amp; and &bull;

### ISSUE THREAD

**Issue by justinradomski** [ashhitch/wp-graphql-yoast-seo#7]
I'm not sure if this is specific to just the title tag field, but I've got an ampersand and bullet character in my title tags and they're showing up as `&amp;` and `&bull;` after fetching from GraphQL.

**Comment by ashhitch** [comment]
@justinradomski thanks for reporting this will take a look at this

**Comment by izzygld** [comment]
@ashhitch should we echo `html_entity_decode(strip_tags( SeoField)) . "\n";`?

**Comment by ashhitch** [comment]
I don't think this is an issue now we are using Yoast's new public API.
![image](https://user-images.githubusercontent.com/2438290/81178624-64fc0a00-8fa0-11ea-9425-597adf55bfc8.png)

Please reopen if you are still having issues.

**Comment by kyleoliveiro** [comment]
@ashhitch I'm still encountering this issue.

Plugin versions I'm using:

- WP GraphQL - Version 0.10.0
- WPGraphql Yoast Seo - Version 4.3.0
- Yoast SEO - Version 14.4.1

**Comment by ashhitch** [comment]
@kyleoliveiro have you got any examples of this happening?

**Comment by kyleoliveiro** [comment]
It seems like its only occurring on taxonomies. For posts its working fine.

**Comment by kyleoliveiro** [comment]
![Capture](https://user-images.githubusercontent.com/4415224/86324766-a1cb4100-bc71-11ea-9d25-6a45385b987d.PNG)

**Comment by ashhitch** [comment]
FIxed by #48 in v4.4.1
