### ISSUE TITLE
Introduce WordPress VIP coding standards and fixes for existing errors

### ISSUE THREAD

**Issue by henrikwirth** [ashhitch/wp-graphql-yoast-seo#70]
See this ticket as a main reference and for discussions: https://github.com/wp-graphql/wp-graphql/issues/1535

WordPress VIP has pretty high coding standards and everyone who will work with VIP in the future will face the same problems as our team right now. It would be great if we could get coding standards up and running with VIP's standards.

Ideally we could setup PHP_Codesniffer with all the configurations of them and let a bot check run through it before merging PRs.

We will attempt to setup everything and also fix major errors, so that we will be able to use WPGraphQL in the future. It would be great if some maintainers can share some of their attention on this, so we don't end up breaking stuff.

Also this is obviously open for discussion, we would just use that PR for our purposes anyways, but would greatly appreciate if it would make it into the main repos best practices.

**References:** 
- https://wpvip.com/documentation/how-to-install-php-code-sniffer-for-wordpress-vip/
- https://github.com/Automattic/VIP-Coding-Standards/tree/master/WordPress-VIP-Go

**Comment by ashhitch** [comment]
Hey, this is something I have been thinking about, so happy to get any help getting it going.

**Comment by ashhitch** [comment]
Hey @henrikwirth,
So I started to look into this and have merged in some linting to try help.
One thing that I need to get my head around is the VIP specific functions. 
FOr example `wpcom_vip_attachment_url_to_postid` is there a good way of detecting VIP to then use these functions instead of the standard attachment_url_to_postid?

**Comment by henrikwirth** [comment]
Heya, I think we already fixed the major stuff in this. @oriooctopus wanted to create a PR on this here.

**Comment by ashhitch** [comment]
Ok cool, I will await that PR.

**Comment by oriooctopus** [comment]
@ashhitch we'll ask VIP for what the best way to do this would be since we are in active communication with them. Potentially something like 
`if (function_exists(wpcom_vip_attachment_url_to_postid)` but I have a feeling like the code checker will still be angry

**Comment by henrikwirth** [comment]
@ashhitch There is a set of helpers here: https://github.com/Automattic/vip-go-mu-plugins/blob/master/vip-helpers/vip-caching.php

Maybe we can do something like:

```
if ( ! function_exists('wpcom_vip_attachment_url_to_postid') ) {

    function wpcom_vip_attachment_url_to_postid( $url ) {
	$cache_key = wpcom_vip_attachment_cache_key( $url );
	$id        = wp_cache_get( $cache_key );
	if ( false === $id ) {
		$id = attachment_url_to_postid( $url );
		if ( empty( $id ) ) {
			wp_cache_set( $cache_key , 'not_found', 'default', 12 * HOUR_IN_SECONDS + mt_rand( 0, 4 * HOUR_IN_SECONDS ) );
		} else {
			wp_cache_set( $cache_key , $id, 'default', 24 * HOUR_IN_SECONDS + mt_rand( 0, 12 * HOUR_IN_SECONDS ) );
		}
	} elseif ( 'not_found' === $id ) {
		return false;
	}
	return $id;
    }
}
