### ISSUE TITLE
Can't fetch frontpage seo

### ISSUE THREAD

**Issue by wassim** [ashhitch/wp-graphql-yoast-seo#76]
<img width="698" alt="Capture d’écran 2020-11-28 à 20 18 41" src="https://user-images.githubusercontent.com/14947638/100524270-fa6a2000-31b6-11eb-926a-2ac7e4a67a0f.png">

```
query MyQuery {
  seo {
    openGraph {
      frontPage {
        title
        description
      }
    }
  }
}
```

Result in:

```
{
  "data": {
    "seo": {
      "openGraph": {
        "frontPage": {
          "title": "",
          "description": ""
        }
      }
    }
  },
}
```

**Comment by ashhitch** [comment]
@wassim thanks for reporting this.
Can I check which version of Yoast and this plugin your running?
also what setting do you have for:
![image](https://user-images.githubusercontent.com/2438290/100545038-a6604980-3251-11eb-8179-b1dc98a143df.png)
