### ISSUE TITLE
Returning social images

### ISSUE THREAD

**Issue by nathobson** [ashhitch/wp-graphql-yoast-seo#8]
Firstly, great work on the plugin so far.

I had a suggestion around the social images (Open Graph and Twitter) that get returned. It would be great if we could return them as as a meditaItem. At the moment, they're just being returned as strings that point back to the WordPress instance, rather than Gatsby locally. 

I had a go at getting this working but couldn't crack it. I figure we could use the type `MediaItem` rather than `String` but I just couldn't find enough documentation around what I actually needed to pass to it.

At the moment, I can see the plugin is using `_yoast_wpseo_opengraph-image` to grab the URL and I also see in the database that `_yoast_wpseo_opengraph-image-id` is available to get the ID of the media item. Just can't tie it all together. I'll submit a PR though if I get it figured out!

**Comment by robmarshall** [comment]
Just came across this issue. I found this post helpful when working with similar issues within my Gatsby build. Might help...

https://dev.to/nevernull/gatsby-with-wpgraphql-acf-and-gatbsy-image-72m

**Comment by nathobson** [comment]
Thanks for the reply @robmarshall. Did you get the two (this plugin and images via that technique) hooked up? That's actually exactly how I'm dealing with the images on my site but as I'm only getting the URL back from the plugin, I can't really do much with it - it's not returned as a `mediaItem`.

**Comment by robmarshall** [comment]
I haven't tried it yet. This is probably something I will be looking at in a few days. Thought I would just pass the link over while I remembered!

If it is not returned as a media item, could you use the image URL, and create a resolver that finds that URL from the media library resolver (that you currently use)?.

If I can get it to work I'll let you know!

**Comment by nathobson** [comment]
Appreciate it. Likewise, I'll give it another crack with fresh eyes over the next few days and report back.

**Comment by nathobson** [comment]
Just to clarify, the image itself is available as a media item if you were to separately query for it i.e.

```
query MyQuery {
  wordPress {
    mediaItemBy(mediaItemId: 508) {
      sourceUrl
      imageFile {
        childImageSharp {
          id
        }
      }
    }
  }
}
```

Would return:

```
{
  "data": {
    "wordPress": {
      "mediaItemBy": {
        "sourceUrl": "http://example.test/app/uploads/2019/11/image.jpg",
        "imageFile": {
          "childImageSharp": {
            "id": "cccf294c-6f77-517d-b365-a7ee335245f6"
          }
        }
      }
    }
  }
}
```

But when you query the against the wp-graphql-yoast-seo plugin, for example:

```
query MyQuery {
  wordPress {
    pageBy(pageId: 2) {
      seo {
        opengraphImage
      }
    }
  }
}
```

You just get back the source URL:

```
{
  "data": {
    "wordPress": {
      "pageBy": {
        "seo": {
          "opengraphImage": "http://example.test/app/uploads/2019/10/image.jpg"
        }
      }
    }
  }
}
```

**Comment by robmarshall** [comment]
Indeed.

So I am wondering if it is possible to create a resolver to query against sourceURL of the mediaItem. Using the opengraphImage url (if existing).

If it exists, copy the mediaItem node and add it to the SEO node.

It would be better to update the plugin to return the ID. But I do not know enough about the backend of wpGraphQl.

Using something like this: https://www.gatsbyjs.org/blog/2019-03-18-releasing-new-schema-customization/#the-type-builder-api

Maybe.

**Comment by ashhitch** [comment]
@nathobson  and @robmarshall 
I have been working on this feature to provide images as MediaItems. 
As it will be a breaking change I will release this as a major version bump soon.

Would be great if you could test it out.
https://github.com/ashhitch/wp-graphql-yoast-seo/releases/tag/v3.0.0

**Comment by nathobson** [comment]
This is great! I've just had a play around with it and works as expected and all resolves via `ChildImageSharp` for full Gatsby Image goodness :)

**Comment by ashhitch** [comment]
V3 resolved this issue
