### ISSUE TITLE
Page SEO returns encoded special characters

### ISSUE THREAD

**Issue by GideonWislang** [ashhitch/wp-graphql-yoast-seo#83]
Looks like I'm getting encoded special characters for page. Thought this might have been fixed in the past but seems to be broken again.

Here's my query and what it returns.
![image](https://user-images.githubusercontent.com/5721763/111082323-83da0e00-856c-11eb-85c6-8146b3034e49.png)

Example shown is requesting titles but same issue occurs when requesting desc's
Let me know if there's anymore more you want me to provide.

Cheers!

**Comment by ashhitch** [comment]
@GideonWislang 
How are the characters stored in the DB? or viewable in WP admin?

this is what I get 
![image](https://user-images.githubusercontent.com/2438290/111627636-2998b180-87e7-11eb-9c85-47dbeb0c4951.png)

![image](https://user-images.githubusercontent.com/2438290/111627763-53ea6f00-87e7-11eb-973a-4945a363df60.png)

**Comment by rodrigo-arias** [comment]
Hi @ashhitch, I have the same problem. WordPress stores the `blogname` in `wp_options` encoding the html entities, I would expect the content to be decoded for GraphQL.

I think Json it's decoding several content in WPGraphQL. Maybe [this](https://github.com/wp-graphql/wp-graphql/blob/f15bbb5044066c3d09dc96cd5c23acbade1a5727/src/Model/Model.php#L502) is useful. Thanks

**Comment by rodrigo-arias** [comment]
Hi @ashhitch I have seen that the workflow closed the issue, but the error is still there. Have you had a chance to review it? Thanks

**Comment by ashhitch** [comment]
Sorry, I have yet to get to the bottom of this but it will be the next job on this plugin.

**Comment by ashhitch** [comment]
Sorry this one was a long time coming - #97  and release v4.14.00 fixes this issue

**Comment by rodrigo-arias** [comment]
I'm a little late here, but I just wanted to say that I tried it and it works fine. Thanks for solving it @ashhitch
