### ISSUE TITLE
 Notice: Undefined property: WP_Taxonomy::$graphql_single_name

### ISSUE THREAD

**Issue by stijlbreuk** [ashhitch/wp-graphql-yoast-seo#87]
Hi,

I get the following notice when defining custom taxonomies: 
` Notice: Undefined property: WP_Taxonomy::$graphql_single_name in wp-graphql-yoast-seo.php on line 935`

**Comment by ashhitch** [comment]
Hey
Have you set the graphql_single_name for the custom taxonomy?

**Comment by stijlbreuk** [comment]
Thanks for your reply. We did set all single and plural names for the custom taxonomies, using the [WPGraphQL Custom Post Type UI plugin](https://github.com/wp-graphql/wp-graphql-custom-post-type-ui). 

![Screenshot 2021-03-23 at 08 04 19](https://user-images.githubusercontent.com/43994518/112106793-66312800-8bae-11eb-8349-973963f1a48e.png)
