### ISSUE TITLE
Get Yoast Primary Custom Taxonomy item - Enhancement

### ISSUE THREAD

**Issue by robmarshall** [ashhitch/wp-graphql-yoast-seo#90]
Hi,

Thanks for the work you have already done on this plugin. Super helpful!

Is it possible to add functionality like in this ticket: [Get Yoast Primary Category in Post ](https://github.com/ashhitch/wp-graphql-yoast-seo/issues/57), but for custom Taxonomies?

Thanks,
Rob

**Comment by ashhitch** [comment]
@robmarshall 
This should already work like this
```graphql
query GetItemsWithIsPrimary {
  items {
    nodes {
      title
      slug
      features {
        edges {
          isPrimary
          node {
            name
            count
          }
        }
      }
    }
  }
}

```

**Comment by robmarshall** [comment]
Apoligies, I missed out a potentially vital piece of info. This query is on a custom post type.

So I am looking to pull the primary item from a custom taxonomy, off a custom post type.

It seems isPrimary does not exist on this type of query.

**Comment by ashhitch** [comment]
@robmarshall sorry for the delay .. but could you give me an example of the query you would like / expect to run?

**Comment by robmarshall** [comment]
I am trying to run this:
```
{
  allWpFoodAndDrink {
    nodes {
      foodDrinkCategories {
        nodes {
          slug
          isPrimary
        }
      }
    }
  }
}
```

However, just checked the standard post query within my graphQL inspector (after Gatsby build) and no categories have an 'edges' array. Only have 'nodes'. Maybe this is the issue?

i.e. I can see:

```
{
  allWpPost {
    nodes {
      categories {
        nodes {
					slug
        }
        // But no edges are visible here
      }
    }
  }
}
```

Does that help?

**Comment by Rupsnigdha** [comment]
any updates on this? I don't see isPrimary in the IDE
