### ISSUE TITLE
Unable to install wp-graphql-yoast-seo using composer

### ISSUE THREAD

**Issue by dev-catalyst** [ashhitch/wp-graphql-yoast-seo#92]
I'm trying to install this plugin using composer on one of my websites. But, I'm unable to do so as I'm getting this error.

```                                                                                                           
  [Composer\Downloader\TransportException]                                                                  
  Invalid credentials for 'https://my.yoast.com/packages/p2/ashhitch/wp-graphql-yoast-seo.json', aborting.
```

I have checked my credentials multiple times but to no avail. I have also tried using both the username and password as well as token but still, the credentials are showing as invalid.

![Screenshot 2021-04-15 at 6 47 09 PM](https://user-images.githubusercontent.com/38284073/114876559-13006d00-9e1c-11eb-966a-c32ae0bcf985.png)

This is my composer version
`Composer version 2.0.11 2021-02-24 14:57:23`

Please help find that what could be the possible cause for this error?
Thank you!

**Comment by ashhitch** [comment]
this plugin should not require any logins as it is public...
are you trying to install Yoast premium also? if so you need a token todo that I belive

**Comment by dev-catalyst** [comment]
@ashhitch Yoast premium is already installed on the website.
`"yoast/wordpress-seo-premium": "12.9.2"`

Can that be the issue? And if yes, what credentials do I need to use in that case?

**Comment by ashhitch** [comment]
Sorry about the delay in getting back to you her is some helpful info on how todo this:
https://yoast.com/help/how-to-install-yoast-plugins-using-composer/
