### ISSUE TITLE
Include the Est. reading time?

### ISSUE THREAD

**Issue by izzygld** [ashhitch/wp-graphql-yoast-seo#95]
<img width="555" alt="Screen Shot 2021-04-21 at 16 09 25" src="https://user-images.githubusercontent.com/12534341/115558960-ec2eb480-a2bb-11eb-84ac-e7bee08a2277.png">

Any way we can retrieve the **Est. reading time**?

**Comment by ashhitch** [comment]
```graphql 
seo {
readingTime
}
```

should return this

**Comment by izzygld** [comment]
thank you.
