### ISSUE TITLE
HTML entities

### ISSUE THREAD

**Issue by benknight** [ashhitch/wp-graphql-yoast-seo#96]
I'm using WP GraphQL with Next.js and my page titles all have raw HTML entities in them like `Page &ndash; Site Name`

It would make sense for this plugin to decode all HTML entities in strings, right? GraphQL being a data API, it need not concern itself with escaping data, that's the rendering engine's job.

**Comment by ashhitch** [comment]
#97  and release v4.14.00 fixes this issue
