### ISSUE TITLE
Is logo/companyLogo working?

### ISSUE THREAD

**Issue by matepaiva** [ashhitch/wp-graphql-yoast-seo#98]
Hi, first of all thank you for the hard work!

I have set the company logo in the configuration wizard for my website (and it shows there), but when I query it from the GraphQL IDE, the `logo` / `companyLogo` / `personLogo` is empty. 

Do you think it could be a bug or maybe I am doing something wrong?

```
# VERSIONS
"ashhitch/wp-graphql-yoast-seo": "^4.14",
"wpackagist-plugin/wordpress-seo": "^16.1",
```

query:
```gql
{
  seo {
    schema {
      logo {
        id
        sourceUrl
      }
      companyLogo {
        id
        sourceUrl
      }
      personLogo {
        id
        sourceUrl
      }
    }
  }
}
```

result:
```json
{
  "data": {
    "seo": {
      "schema": {
        "logo": null,
        "companyLogo": null,
        "personLogo": null
      }
    }
  }
}
```

Thank you! :)

**Comment by ashhitch** [comment]
@matepaiva Thanks for taking the time to raise this... everything is looking ok on my test site:
![image](https://user-images.githubusercontent.com/2438290/119838254-2adb0e80-befb-11eb-9b93-695bdfc08ddc.png)

under SEO > Search appearance do you see your image?
![image](https://user-images.githubusercontent.com/2438290/119838426-4f36eb00-befb-11eb-8434-f8c54f636571.png)

**Comment by matepaiva** [comment]
I can confirm the problem is on my side. Thank you for your feedback. I am closing this issue.
